apiVersion: v1
kind: Pod
metadata:
  name: posgresql-client
  namespace: postgresql
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: posgresql-client
    image: postgres:11-alpine
    imagePullPolicy: IfNotPresent
    resources:
      # limits:
      #   cpu: "500m"
      #   memory: "512Mi"
      requests:
        cpu: "10m"
        memory: "32Mi"

